### ISSUE TITLE
Include dependency on OpenStudio Model Articulation Gem

### ISSUE THREAD

**Issue by nllong** [BuildingSync/BuildingSync-gem#12]
Remove the use of OS_Lib methods and import methods from https://github.com/NREL/openstudio-model-articulation-gem

**Comment by TMaile** [comment]
- [x] add `create_typical_building_from_model_bricr` measure resource file to the DA branch of openstudio-model-articulation-gem
- [x] link to this instance from BuildingSync Gem
- [x] remove the measure from the BuuildingSync Gem

**Comment by TMaile** [comment]
This is completed in 99410a2
