### ISSUE TITLE
EDV (using BSync v0.2.0) related question

### ISSUE THREAD

**Issue by JanghyunJK** [BuildingSync/BuildingSync-gem#127]
I was testing [EDV workflow](https://github.com/NREL/edv_synthetic_smart_meter_data) lately and found something that was missing in tag version `v0.2.0` but which was available in the current (as of today) `develop` branch. Summary below.

- EDV plan is to use BuildingSync-gem v0.2.0 (for now) for creating EP/OS models

- but when I run below on EDV's side,
`translator = BuildingSync::Translator.new(xml_file_path, out_path, epw_file_path, standard, false)`  

- I was getting the following error
`Error occurred while processing C:/Users/JKIM4/Documents/GitHub/edv-experiment-1/workflow_results/Add_Measured_Data_Files/Panther_office_Karla.xml with message: uninitialized constant BuildingSync::Generator
Did you mean?  Enumerator`

- was tracking down why it wasn't accepting BuildingSync::Generator and found out `translator.rb` wasn't including `require 'buildingsync/generator'` in v0.2.0 while it was there in `develop` branch as shown [here](https://github.com/BuildingSync/BuildingSync-gem/blob/fe698bbe97d9241e12e24437c27af4600cd864fd/lib/buildingsync/translator.rb#L41) 

- so was wondering,
  - if this difference was intended for v0.2.0
  - or if `require 'buildingsync/generator'` could also be added in v0.2.0

Let me know if I'm just at the wrong place for this issue or if you have any questions/comments/suggestions. Thanks!!

**Comment by JanghyunJK** [comment]
tagging @lainsworth8801

**Comment by nllong** [comment]
@aviveiros11  -- are you able to tackle this issue?

**Comment by aviveiros11** [comment]
@nllong yes!  Just have to clear some things off of my plate first.  Will investigate when I can.

**Comment by nllong** [comment]
sounds good. let me know what you find.

**Comment by JanghyunJK** [comment]
@aviveiros11 any updates on this yet?

**Comment by aviveiros11** [comment]
> @aviveiros11 any updates on this yet?

Haven't had time but will move this up on my priority list of to-dos!

**Comment by JanghyunJK** [comment]
> > @aviveiros11 any updates on this yet?
> 
> Haven't had time but will move this up on my priority list of to-dos!

got it, thanks Rock Lee.
