### ISSUE TITLE
Models can't be created when sub building type is determined by number of floors

### ISSUE THREAD

**Issue by KaiyuSun** [BuildingSync/BuildingSync-gem#137]
Models can't be created when sub building type (e.g. Multifamily - MidriseApartment/HighriseApartment) is determined by comparing its number of floors with predefined thresholds. Source code: 
https://github.com/BuildingSync/BuildingSync-gem/blob/ab24be822467243da8882eaaf921242e75c2cc42/lib/buildingsync/model_articulation/spatial_element.rb#L207-L214
This is caused by total_number_floors not being able to obtain the right value. The reason is located below:

https://github.com/BuildingSync/BuildingSync-gem/blob/ab24be822467243da8882eaaf921242e75c2cc42/lib/buildingsync/model_articulation/building_section.rb#L170-L173
@number_floors is not defined, should change to @num_stories, which is defined via initialize. As a consequence, the input total_number_floors gets nil.

.

**Comment by haneslinger** [comment]
https://github.com/BuildingSync/BuildingSync-gem/pull/145/files
