### ISSUE TITLE
Remove weather files from the repository

### ISSUE THREAD

**Issue by TMaile** [BuildingSync/BuildingSync-gem#14]
I'm not fond of having the weather files in this Gem. I don't have a better idea at the moment. In python there is a post-install command that runs and I'm wondering if we could do something similar where upon installing the gem a post install command runs and installed the weather files.

Still needs some investigation on how this would work.

**Comment by TMaile** [comment]
- [ ] Investigate if there is something like a post-install command in ruby

- [x] Find source of weather files BCL?

- [ ] Write code to fetch weather files during post install command to copy them somewhere local

**Comment by TMaile** [comment]
What about we download the weather files directly from BCL only once they are needed?

**Comment by macumber** [comment]
In my opinion the user should have to provide their own weather files, this gem does not have to offer that functionality

**Comment by TMaile** [comment]
this needs discussion

**Comment by TMaile** [comment]
done, using Standards-Gem for weather files from Climate Zone, we want to add possibility to download specific weather files based on the location from BCL.  see #20
