### ISSUE TITLE
We are not mapping CA climate zones well

### ISSUE THREAD

**Issue by haneslinger** [BuildingSync/BuildingSync-gem#153]
we will need to figure out why the string we get for the climate zone template is not correct. The script looks for 'CEC T24-CEC6A' and the '6A' portion is taken from the climate zone specified in the XML, which is '6A'. If we look in the climate zone map, we see that 'CEC T24-CEC__' names end in digits but never letters. Maybe the Title 24 climate zone definitions cannot be directly mapped to the typical climate zone codes. Is anything implemented in the code to decide which template should be used based on the climate zone specified in the XML?

**Comment by ThibaultMarzullo** [comment]
This behavior is expected in [this](https://github.com/BuildingSync/BuildingSync-gem/blob/10265338ab30019a7a9d615ae5cc21bbb5019aee/spec/tests/translator_sizing_run_spec.rb#L162-L175) test
