### ISSUE TITLE
Golden Test File - Processing large bldg - small bldg occupancy type: laboratory testing

### ISSUE THREAD

**Issue by TMaile** [BuildingSync/BuildingSync-gem#23]
The Golden Test File has two buildings. Since we are focusing on generating only one building for now, we developed code to pick the largest building by floor area. 
This also circumvents the issue with the occupancy type of the small building set to "Laboratory-Testing" which is not supported in any of the standards we are considering,

**Comment by macumber** [comment]
I think the right approach here would be to simulate both buildings in a single OSM, I created a ticket to make a design decision on this: https://github.com/BuildingSync/BuildingSync-gem/issues/28

**Comment by TMaile** [comment]
We decided that for files with two buildings we will raise an error that this is the case.
