### ISSUE TITLE
Scenario processing: Measures not found in DC GSA Headquarters.xml

### ISSUE THREAD

**Issue by TMaile** [BuildingSync/BuildingSync-gem#24]
The following measures could not be processed and I could not find them via a quick search in the usual gems:
- Name: Other -- Description: HVAC Scheduling Control
- Name: Retrofit with T-8 -- Description: Lighting Retrofit
- Name: Other -- Description: Air Side and Water Side Economizer Maintenance
- Name: Upgrade operating protocols, calibration, and/or sequencing -- Description: Demand Controlled Ventilation

**Comment by macumber** [comment]
I don't know what the general desire is, should we have an OpenStudio Measure for each possible BuildingSync Measure?  What are we supposed to do with `MeasureName = Other`?

**Comment by corymosiman12** [comment]
@nllong can we close this? I think no longer relevant.
