### ISSUE TITLE
Extend testing of comparing to OSM file to compare IDF files

### ISSUE THREAD

**Issue by TMaile** [BuildingSync/BuildingSync-gem#27]
Currently we are generating an OSM file at the site level and compare it to an earlier version of that file, by making sure the file size is within 1 byte. 
In order to detect smaller differences between those files/models, we need to compare IDF files

**Comment by TMaile** [comment]
this one is also done, we convert the two osm files now to idf and compare those line by line. Just the numbering of sub surfaces is not consistent so we ignore the names of those.

**Comment by macumber** [comment]
Let us know about inconsistency in the idf, those are os bugs to file issues on
