### ISSUE TITLE
Test files refer to schema in incorrect relative location

### ISSUE THREAD

**Issue by macumber** [BuildingSync/BuildingSync-gem#29]
BuildingSync-gem\spec\files\DC GSA Headquarters.xml refers to a schema at ../BuildingSync.xsd

`<BuildingSync xmlns="http://buildingsync.net/schemas/bedes-auc/2019" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://buildingsync.net/schemas/bedes-auc/2019 ../BuildingSync.xsd">`

However, this schema does not exist in the repository.  We should either include the schema in the repo or point to it at an online location.

**Comment by TMaile** [comment]
this issue is fixed now.
