### ISSUE TITLE
Don't include OpenStudio Module in classes

### ISSUE THREAD

**Issue by macumber** [BuildingSync/BuildingSync-gem#30]
The OpenStudio Module is huge and not meant to be mixed into classes.  Don't include it in classes like:

https://github.com/BuildingSync/BuildingSync-gem/blob/DA/lib/buildingsync/model_articulation/spatial_element.rb#L44

**Comment by macumber** [comment]
This is causing issues on the SEAT EDV project

**Comment by TMaile** [comment]
I removed the 'include OpenStudio' from the spatial element class as requested.
