### ISSUE TITLE
Use local version of EPW file before download from BCL

### ISSUE THREAD

**Issue by TMaile** [BuildingSync/BuildingSync-gem#32]
Is there something like a local component library that would make it easy to use local instances of EPW files?

**Comment by nllong** [comment]
@macumber -- can we use the measure manager for this?

**Comment by TMaile** [comment]
@mrigeshgupta 
- please define a common weather directory (spec/weather)
- use a dictionary or hash to store the mapping between weather id - state and city to weather file name.
- store this hash in a JSON file
- before downloading check the JSON file if the key exists
- if we have a weather file in the hash then check if it is still available, if it is use it
- otherwise download the weather file and add an entry to the hash/JSON file

**Comment by TMaile** [comment]
Mrigesh completed this
