### ISSUE TITLE
Attributes conditioned_floor_area or heated_and_cooled_floor_area used?

### ISSUE THREAD

**Issue by corymosiman12** [BuildingSync/BuildingSync-gem#45]
https://github.com/BuildingSync/BuildingSync-gem/blob/50edf2060dd5d86bebfde5663d3aac3ef3711b9e/lib/buildingsync/model_articulation/spatial_element.rb#L90-L94

Hey @TMaile, are these defined anywhere?  Seems maybe they were previous attribute names or something, or I missed them?

**Comment by TobiasMaile** [comment]
@corymosiman12 you are correct, these area attributes are left overs from a previous version, I just fixed this issue and used attributes that are actually use.

**Comment by TMaile** [comment]
resolved by https://github.com/BuildingSync/BuildingSync-gem/commit/0948bd54de19c73a356df93bf4e97933795625c0
