### ISSUE TITLE
occupancy_type vs occupancy_classification?

### ISSUE THREAD

**Issue by corymosiman12** [BuildingSync/BuildingSync-gem#46]
https://github.com/BuildingSync/BuildingSync-gem/blob/50edf2060dd5d86bebfde5663d3aac3ef3711b9e/lib/buildingsync/model_articulation/building_section.rb#L115

https://github.com/BuildingSync/BuildingSync-gem/blob/50edf2060dd5d86bebfde5663d3aac3ef3711b9e/lib/buildingsync/model_articulation/building_section.rb#L94

Hey @TMaile  - seems to me these both access the auc:OccupancyClassification element, so just trying to understand if the have different intentions?

**Comment by TMaile** [comment]
@corymosiman12 good catch. @occupancy_classification is redundant, I just removed it.
