### ISSUE TITLE
Maker Classes

### ISSUE THREAD

**Issue by corymosiman12** [BuildingSync/BuildingSync-gem#47]
@TMaile the class inheritance structure used for the Makers is very confusing.  We have the following:
ModelMakerLevelZero < PhaseZeroWorkflowMaker
PhaseZeroWorkflowMaker < WorkflowMaker
WorkflowMaker < ModelMaker

From my perspective, seems like we should segment methods / properties according to how they are segmented for OSMs and OSWs, namely:
1. ModelMaker should include methods / structures for creating an OSM
1. WorkflowMaker should include methods / structures for defining an OSW using a base OSM

Let's discuss on next call

**Comment by TMaile** [comment]
I further simplified this in the DA_Test branch. 

![image](https://user-images.githubusercontent.com/49325382/70331722-54eccc80-1840-11ea-81c5-e5752870b96f.png)
