### ISSUE TITLE
Translator.write_model_to_xml

### ISSUE THREAD

**Issue by corymosiman12** [BuildingSync/BuildingSync-gem#49]
Exact method name of `write_model_to_xml` isn't necessary, nor for it to live in the `Translator` class (I know we have the `saveXML` in the ModelMaker classes, and maybe this is the eventual intention of this method), but it would be super useful for the OSM to be flushed to the specified file, such that upon write, as many of the characteristics of the model that can be represented in the Schema be translated to xml.  This would make it very valuable for users to understand how the BuildingSync file they provided was interpreted by the gem without needing to open up the `.osm` file

**Comment by TMaile** [comment]
this is completed for BuildingSync class parameters, this could be extended in the future with also including selected feedback directly from the OpenStudio Model, e.g., space types and floor areas, etc.
