### ISSUE TITLE
question on this line in workflow_maker.rb

### ISSUE THREAD

**Issue by JanghyunJK** [BuildingSync/BuildingSync-gem#57]
https://github.com/BuildingSync/BuildingSync-gem/blob/bb52655ebb8efeca44249277d3fb67ac60b4e610/lib/buildingsync/makers/workflow_maker.rb#L482

So, I was running EDV workflow, and realized baseline OS simulation results were not adding back to xml. Here is a detail description of the [issue](https://github.com/NREL/edv-experiment-1/issues/92).

So I was looking into BuildingSync gem and found that one line in the link above was skipping (if I'm understanding correctly) baseline scenario for adding back to xml files. Is this something that was necessary on BuildingSync gem? or can we comment that line out (or do something else) moving forward?

**Comment by corymosiman12** [comment]
Hey Janghyun - just realized I never received any notifications for your other issue.  For now, can you comment that line out and see it it affects the workflow at all?  I think we need to do some more general maintenance, but let's see if this works for now.

In the meantime, you should be able to clone BuildingSync gem locally, use the `allow_local=true` in the edv-experiment-1 Gemfile to test whether commenting that line out messes anything else up - let me know if that makes sense or you have other questions.

@TMaile any other insights to offer?

**Comment by JanghyunJK** [comment]
Yup, I've tested, and commenting that line seems to be working. I'm actually forking (not sure this is the right term) BuildingSync gem under my name's repo. Hope this is not making any mess on BuildingSync gem side.

**Comment by JanghyunJK** [comment]
actually, I have to comment out this line as well if measured data is already included in the xml

https://github.com/BuildingSync/BuildingSync-gem/blob/bb52655ebb8efeca44249277d3fb67ac60b4e610/lib/buildingsync/makers/workflow_maker.rb#L481

**Comment by corymosiman12** [comment]
Hey @JanghyunJK, two things:

1. Looks like edv-experiment-1 is pulling from `DA` branch on BuildingSync-gem.  I think this issue has already been addressed. Make sure to do a `bundle install` and / or a `bundle update` on your `edv-experiment-1` (and in this case, make sure you ARE NOT using `allow_local=true`.  See if updating / pulling in the new stuff works.  If not, see next bullet.
 https://github.com/BuildingSync/BuildingSync-gem/blob/bb52655ebb8efeca44249277d3fb67ac60b4e610/lib/buildingsync/makers/workflow_maker.rb#L440
1. Let's not plan on you making a new fork of BuildingSync-gem specifically for this.  I'd rather you and I discuss and game plan fixes we need to make to the gem to make sure your stuff is working.  I will email you.

**Comment by TMaile** [comment]
Hi guys, I think you have it well covered by now, it may be just a merge issue that did cause this bug. Let me know if you need more help on this one.

**Comment by JanghyunJK** [comment]
@TMaile  @corymosiman12 
guys, these two lines are two different things.

https://github.com/BuildingSync/BuildingSync-gem/blob/bb52655ebb8efeca44249277d3fb67ac60b4e610/lib/buildingsync/makers/workflow_maker.rb#L440

https://github.com/BuildingSync/BuildingSync-gem/blob/bb52655ebb8efeca44249277d3fb67ac60b4e610/lib/buildingsync/makers/workflow_maker.rb#L482

looks like quick fix is to use the same code in line 440 in line 482.

**Comment by TMaile** [comment]
440 is skipping all scenarios except the Baseline if the "baseline_only" flag is true

482 is within an IF statement that is only called when "baseline_only" is false and skips the Baseline

so I think these are different cases, but if it works this way, granted.

**Comment by JanghyunJK** [comment]
using this branch for fixing.
https://github.com/BuildingSync/BuildingSync-gem/tree/DA_EDV_testing
