### ISSUE TITLE
DO NOT USE PrimaryLightingSystemType element

### ISSUE THREAD

**Issue by corymosiman12** [BuildingSync/BuildingSync-gem#60]
https://github.com/BuildingSync/BuildingSync-gem/blob/d23c6e14e87f816ee76f62b6bc99d56b424506e7/spec/files/L100_Instance1.xml#L142

This element should not exist.  Instead, the `auc:LightingSystem` should have a child `auc:LampType` with one of the sub-elements defined for the L100 level (i.e. `auc:LampType/auc:LinearFluorescent`, `auc:LampType/auc:Incandescent`, etc.)

**Comment by TMaile** [comment]
this is done in the new version of this file called L100_Audit.xml here https://github.com/BuildingSync/BuildingSync-gem/blob/9e242e212afcd6d99349e8c8ab2deb7650db039b/spec/files/L100_Audit.xml#L171
