### ISSUE TITLE
[DA] move NUM_BUILDINGS_PARALLEL  to runner?

### ISSUE THREAD

**Issue by TMaile** [BuildingSync/BuildingSync-gem#62]
the file config.rb.in still contains a constant for the number of buildings that can be run in parallel.

```
 # number of parallel BuildingSync files to run
 NUM_BUILDINGS_PARALLEL = 2
```

Should we also move that to the runner options?

See discussion [here](https://github.com/BuildingSync/BuildingSync-gem/pull/56#discussion_r415970726)

**Comment by corymosiman12** [comment]
Hey Tobias - yes, my understanding would be to pass the same options to the translator.  Use the defaults defined by `runner_config` if nothing passed: https://github.com/NREL/openstudio-extension-gem/blob/develop/lib/openstudio/extension/runner_config.rb#L75
