### ISSUE TITLE
Update selection tool code to pass tests

### ISSUE THREAD

**Issue by TMaile** [BuildingSync/BuildingSync-gem#64]
all three tests of the selection tool are failing:
![image](https://user-images.githubusercontent.com/49325382/91193594-90456900-e6f7-11ea-8f3b-357337c60cc1.png)

make code changes to pass these tests again:

https://github.com/BuildingSync/BuildingSync-gem/blob/7117b72a443496d9d74e93461b597e85664f3bbe/spec/tests/selection_tool_spec.rb#L42

**Comment by corymosiman12** [comment]
Fixed with: 4d6c5c12b440f6be04e53b7d33061b108f742e8c
