### ISSUE TITLE
[DA_Update] OpenStudio 3.0.1 fails to install during travis testing

### ISSUE THREAD

**Issue by TMaile** [BuildingSync/BuildingSync-gem#65]
I am trying to update the DA_update branch to support testing with OpenStudio 3.0.1.

The installation of OpenStudio seems to fail. Below are the details:

![image](https://user-images.githubusercontent.com/49325382/91224613-a9174400-e722-11ea-8753-16adb5e38736.png)

here is the line that defines the OpenStudio version:
https://github.com/BuildingSync/BuildingSync-gem/blob/012ccc9dd8999c5dd40fdff7ec3700f93fadc523/.travis.yml#L11

here is the line that tries to install it:
https://github.com/BuildingSync/BuildingSync-gem/blob/f2129817fa7b6d2b152d66d55b52128feeae0293/.travis.yml#L20

I am not sure if the installation file is missing or the script is outdated.

**Comment by corymosiman12** [comment]
Note that the translator_spec was not working and so I commented it out simply to address this issue.  https://travis-ci.org/github/BuildingSync/BuildingSync-gem/builds/721705060
