### ISSUE TITLE
Run BuildingSync Use Case Validator localy

### ISSUE THREAD

**Issue by macumber** [BuildingSync/BuildingSync-gem#7]
Having trouble accessing online validator from Ruby 2.2.4 due to OpenSSL issues.  Run validator locally to test for now.

@kflemin can you write up or point to some documentation on how to run the validator locally

**Comment by kflemin** [comment]
@macumber you'll have to get a local instance of the selection tool running locally.  Follow readme instructions here: https://github.com/BuildingSync/selection-tool.  import schema v1.0.0, then import use case.  after that you should be able to validate xml's using the API: https://github.com/BuildingSync/selection-tool#validator-api.

**Comment by nllong** [comment]
Is this just a temporary fix?

**Comment by macumber** [comment]
Yes, there are a few potential solutions but they are longer term and we don't want to hold up @mrigeshgupta.  Here are some ideas:

- Diagnose and fix issues that are impeding OpenSSL connection using Ruby 2.2.4 and OpenStudio 2.x (this is similar to the issues we were having connecting to BCL)
- Switch to Ruby 2.5.1 and OpenStudio 3.x which will hopefully allow connections
- Create a BuildingSync Use Case Validator Gem that would allow validation without web connection

**Comment by TMaile** [comment]
With Katherine's help we found a workaround to bypass the SSL issue
