### ISSUE TITLE
Define ASHRAE Level 1 Use Case

### ISSUE THREAD

**Issue by macumber** [BuildingSync/BuildingSync-gem#8]
Need to define this in format for the use case validator

**Comment by TMaile** [comment]
This is the closest definition we have on the BRICR Phase 0, 1, 2 phase fields.  The document is in terms of the Audit Template Fields (user interface which authors BuildingSync) but the mapping to BuildingSync fields should be possible.  We have fields defined for Phase 0 and Phase 2, haven’t defined Phase 1 exactly but it is somewhere in between. Conceptually, the three phases are listed below:
 
    Phase 0 – simplified models from public records, building level
    Phase 1 – based on quick visit, phone call, looking at google maps.  Have information about subsections and types of equipment
    Phase 2 – based on actual ASHRAE level 2 audit, each system is cataloged and described.  

 These phases are also described in this document: https://www.researchgate.net/publication/326682062_The_BayREN_Integrated_Commercial_Retrofits_BRICR_Project_An_Introduction_and_Preliminary_Results

**Comment by TMaile** [comment]
some ideas for ASHRAE Level 1:
- ASHRAE Level 1: if > 1 subsection
- ASHRAE Level 1: Principle HVAC Type & Principle Lighting Type (lighting controls)
- ASHRAE Level 1: maybe constructions?

**Comment by TMaile** [comment]
see added a csv to the repro that described the ASHARE level 1 use case based on our mapping developed earlier: [BuildingSync_ASHRAE_Level_1.csv](https://github.com/BuildingSync/BuildingSync-gem/blob/DA_Level1_BldgSync2.0/use_cases/BuildingSync_ASHRAE_Level_1.csv)
