### ISSUE TITLE
Error when Climate Zone specified at the Building Level

### ISSUE THREAD

**Issue by corymosiman12** [BuildingSync/BuildingSync-gem#89]
I install the BSync-gem using the gemfile here:

https://github.com/corymosiman12/energy-modeling/blob/master/Gemfile

I then attempt to run the `lib/run_analysis.rb` using the file: https://github.com/BuildingSync/TestSuite/blob/develop/schematron/v2.2.0/exemplary_files/L000_OpenStudio_Pre-Simulation_02.xml

Get the following error:
```
Traceback (most recent call last):
	6: from lib/run_analysis.rb:15:in `<main>'
	5: from lib/run_analysis.rb:12:in `baseline_creation'
	4: from /Users/cmosiman/new-test/energy-modeling/.bundle/install/ruby/2.5.0/bundler/gems/BuildingSync-gem-982f28c193df/lib/buildingsync/translator.rb:118:in `write_osm'
	3: from /Users/cmosiman/new-test/energy-modeling/.bundle/install/ruby/2.5.0/bundler/gems/BuildingSync-gem-982f28c193df/lib/buildingsync/makers/model_maker.rb:71:in `generate_baseline'
	2: from /Users/cmosiman/new-test/energy-modeling/.bundle/install/ruby/2.5.0/bundler/gems/BuildingSync-gem-982f28c193df/lib/buildingsync/model_articulation/facility.rb:127:in `generate_baseline_osm'
	1: from /Users/cmosiman/new-test/energy-modeling/.bundle/install/ruby/2.5.0/bundler/gems/BuildingSync-gem-982f28c193df/lib/buildingsync/model_articulation/site.rb:275:in `generate_baseline_osm'
/Users/cmosiman/new-test/energy-modeling/.bundle/install/ruby/2.5.0/bundler/gems/BuildingSync-gem-982f28c193df/lib/buildingsync/model_articulation/building.rb:542:in `set_weather_and_climate_zone': Error : epw_file_path is nil and no way to set from Site or Building parameters. (RuntimeError)
```

I move the climate zone then to the site level and it works.  A climate zone defined at the building level should not cause this error.  Please do the following:
- Abstract out the following methods from the `Site` object to the `SpatialElement` (or maybe create some sort of mixin for these methods specifically if it doesn't make sense to include them in the `SpatialElement`):
  - `read_climate_zone`
  - `read_weather_file_name`
  - `read_city_and_state_name`
  - `read_site_other_details`
  - `read_latitude_and_longitude`
- Make sure all those methods get run through at both the `Site` and `Building` level during the initialization phase

**Comment by TMaile** [comment]
fixed in #91
