### ISSUE TITLE
Determine how to set the standard used in translation

### ISSUE THREAD

**Issue by macumber** [BuildingSync/BuildingSync-gem#9]
Currently this is hard wired to use the CBES T24 standard.  However in other cases users may want to use a different standard

**Comment by macumber** [comment]
May need to specify openstudio-standards 0.2.9 in https://github.com/BuildingSync/BuildingSync-gem/blob/develop/buildingsync.gemspec to use CBES T24

**Comment by TMaile** [comment]
T24 and ASHREA 90.1 are now available options, passed in as a parameter to the Translator initialization method
